"""Init command - workspace initialization like Claude CLI."""

import os
import typer
from pathlib import Path
from rich.panel import Panel
from rich.prompt import Prompt, Confirm
from rich import box

from agent.cli.console import console, Icons, print_success, print_error, print_info


def init(
    path: str = typer.Argument(".", help="Path to initialize (defaults to current directory)"),
    force: bool = typer.Option(False, "--force", "-f", help="Overwrite existing config"),
):
    """Initialize LocalCowork in the current directory.
    
    Creates a .localcowork/ folder with project-specific settings.
    Similar to 'claude init' or 'git init'.
    """
    workspace_path = Path(path).resolve()
    config_dir = workspace_path / ".localcowork"
    config_file = config_dir / "config.yaml"
    
    console.print()
    console.print(Panel.fit(
        f"[bold cyan]{Icons.ROBOT} LocalCowork Init[/bold cyan]\n\n"
        f"[dim]Workspace:[/dim] {workspace_path}",
        border_style="cyan",
        box=box.ROUNDED,
    ))
    console.print()
    
    # Check if already initialized
    if config_file.exists() and not force:
        print_info("Already initialized. Use --force to reinitialize.")
        console.print(f"[dim]Config: {config_file}[/dim]")
        raise typer.Exit(code=0)
    
    # Create config directory
    config_dir.mkdir(parents=True, exist_ok=True)
    
    # Interactive setup
    console.print("[bold]Configure your workspace:[/bold]")
    console.print()
    
    # Model selection
    from agent.llm.client import check_ollama_health, list_models
    from agent.config import settings
    
    default_model = settings.ollama_model
    healthy, _ = check_ollama_health()
    
    if healthy:
        available_models = list_models()
        if available_models:
            console.print(f"[dim]Available models: {', '.join(available_models[:5])}{'...' if len(available_models) > 5 else ''}[/dim]")
            model = Prompt.ask(
                "Model to use",
                default=default_model if default_model in available_models else (available_models[0] if available_models else "llama3"),
            )
        else:
            model = Prompt.ask("Model to use", default="llama3")
            print_info("No models found. Install with: ollama pull llama3")
    else:
        model = Prompt.ask("Model to use", default="llama3")
        print_info("Ollama not running. Start with: ollama serve")
    
    # Project description (for context)
    description = Prompt.ask(
        "Project description (optional)",
        default="",
    )
    
    # Create config file
    config_content = f"""# LocalCowork workspace configuration
# Generated by 'localcowork init'

# AI Model settings
model: {model}

# Project context (used to help the AI understand your project)
description: |
  {description if description else "A LocalCowork workspace"}

# Workspace settings
workspace:
  # Files/folders to ignore when reading context
  ignore:
    - .git
    - .venv
    - __pycache__
    - node_modules
    - "*.pyc"
    - ".localcowork"
  
  # Max file size to read (bytes)
  max_file_size: 100000

# Safety settings
safety:
  # Require approval before executing tasks
  require_approval: false
  
  # Allow shell commands
  allow_shell: true
  
  # Sandbox Python execution (requires Docker)
  sandbox_enabled: true
"""
    
    config_file.write_text(config_content)
    
    # Create .gitignore for localcowork folder
    gitignore = config_dir / ".gitignore"
    gitignore.write_text("# Ignore task history and logs\nhistory/\n*.log\n")
    
    # Create CLAUDE.md equivalent - instructions file
    instructions_file = config_dir / "INSTRUCTIONS.md"
    if not instructions_file.exists() or force:
        instructions_content = f"""# LocalCowork Instructions

This file contains instructions for the AI when working in this project.
Edit this to customize AI behavior for your specific project.

## Project Overview

{description if description else "Describe your project here."}

## Coding Guidelines

- Follow existing code style
- Add comments for complex logic
- Write tests for new features

## Important Files

- List key files the AI should know about

## Don'ts

- Don't modify configuration files without asking
- Don't delete files without confirmation
"""
        instructions_file.write_text(instructions_content)
    
    console.print()
    print_success("Workspace initialized!")
    console.print()
    console.print("[dim]Created:[/dim]")
    console.print(f"  {Icons.FOLDER} {config_dir}/")
    console.print(f"     config.yaml      [dim]# Workspace settings[/dim]")
    console.print(f"     INSTRUCTIONS.md  [dim]# AI instructions[/dim]")
    console.print()
    console.print("[bold]Next steps:[/bold]")
    console.print(f"  1. Edit [cyan]{config_dir}/INSTRUCTIONS.md[/cyan] to customize AI behavior")
    console.print(f"  2. Run [cyan]localcowork[/cyan] to start chatting")
    console.print(f"  3. Run [cyan]localcowork run 'your task'[/cyan] to execute tasks")
